In [1]:
import torch

In [2]:
t = torch.arange(0, 5 * 4 * 3 * 2)

In [3]:
t

tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
         28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
         42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
         56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
         70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
         84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
         98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
        112, 113, 114, 115, 116, 117, 118, 119])

In [5]:
t2 = t.view(5, 4, 6)
t2

tensor([[[  0,   1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10,  11],
         [ 12,  13,  14,  15,  16,  17],
         [ 18,  19,  20,  21,  22,  23]],

        [[ 24,  25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40,  41],
         [ 42,  43,  44,  45,  46,  47]],

        [[ 48,  49,  50,  51,  52,  53],
         [ 54,  55,  56,  57,  58,  59],
         [ 60,  61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70,  71]],

        [[ 72,  73,  74,  75,  76,  77],
         [ 78,  79,  80,  81,  82,  83],
         [ 84,  85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94,  95]],

        [[ 96,  97,  98,  99, 100, 101],
         [102, 103, 104, 105, 106, 107],
         [108, 109, 110, 111, 112, 113],
         [114, 115, 116, 117, 118, 119]]])

In [7]:
t3 = t2.view(5, 4, 3, 2)
t3

tensor([[[[  0,   1],
          [  2,   3],
          [  4,   5]],

         [[  6,   7],
          [  8,   9],
          [ 10,  11]],

         [[ 12,  13],
          [ 14,  15],
          [ 16,  17]],

         [[ 18,  19],
          [ 20,  21],
          [ 22,  23]]],


        [[[ 24,  25],
          [ 26,  27],
          [ 28,  29]],

         [[ 30,  31],
          [ 32,  33],
          [ 34,  35]],

         [[ 36,  37],
          [ 38,  39],
          [ 40,  41]],

         [[ 42,  43],
          [ 44,  45],
          [ 46,  47]]],


        [[[ 48,  49],
          [ 50,  51],
          [ 52,  53]],

         [[ 54,  55],
          [ 56,  57],
          [ 58,  59]],

         [[ 60,  61],
          [ 62,  63],
          [ 64,  65]],

         [[ 66,  67],
          [ 68,  69],
          [ 70,  71]]],


        [[[ 72,  73],
          [ 74,  75],
          [ 76,  77]],

         [[ 78,  79],
          [ 80,  81],
          [ 82,  83]],

         [[ 84,  85],
          [ 86,  87]

---
http://www.peterbloem.nl/blog/transformers

In [8]:
k = 3
heads = 4

In [12]:
t = []
for head_idx in range(heads):
    t.append(torch.ones(k)*head_idx)
t = torch.cat(t)
tb

tensor([0., 0., 0., 1., 1., 1., 2., 2., 2., 3., 3., 3.])

In [14]:
t.storage()

 0.0
 0.0
 0.0
 1.0
 1.0
 1.0
 2.0
 2.0
 2.0
 3.0
 3.0
 3.0
[torch.FloatStorage of size 12]

In [13]:
t2 = t.view(heads, k)
t2

tensor([[0., 0., 0.],
        [1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]])

A reshaping operation like this reads data into the right-most dimensions sequentially

In [15]:
t3 = t2.view(heads*k)

In [16]:
t3

tensor([0., 0., 0., 1., 1., 1., 2., 2., 2., 3., 3., 3.])

In [22]:
b = 5
t = 4
h = 3
k = 2

In [23]:
num_vecs = b*t*h
num_vecs

60

In [27]:
ten = torch.zeros(b,t,h,k)

In [28]:
ki = 0
for bi in range(b):
    for ti in range(t):
        for hi in range(h):
            ten[bi, ti, hi] = torch.ones(2) * ki
            ki += 1

In [29]:
ten

tensor([[[[ 0.,  0.],
          [ 1.,  1.],
          [ 2.,  2.]],

         [[ 3.,  3.],
          [ 4.,  4.],
          [ 5.,  5.]],

         [[ 6.,  6.],
          [ 7.,  7.],
          [ 8.,  8.]],

         [[ 9.,  9.],
          [10., 10.],
          [11., 11.]]],


        [[[12., 12.],
          [13., 13.],
          [14., 14.]],

         [[15., 15.],
          [16., 16.],
          [17., 17.]],

         [[18., 18.],
          [19., 19.],
          [20., 20.]],

         [[21., 21.],
          [22., 22.],
          [23., 23.]]],


        [[[24., 24.],
          [25., 25.],
          [26., 26.]],

         [[27., 27.],
          [28., 28.],
          [29., 29.]],

         [[30., 30.],
          [31., 31.],
          [32., 32.]],

         [[33., 33.],
          [34., 34.],
          [35., 35.]]],


        [[[36., 36.],
          [37., 37.],
          [38., 38.]],

         [[39., 39.],
          [40., 40.],
          [41., 41.]],

         [[42., 42.],
          [43., 43.]

1-th batch, 2-th timestep, 1-th head

In [46]:
ten[1, 2, 1]

tensor([19., 19.])

In [34]:
ten2 = ten.view(b*h, t, k)
ten3 = ten.transpose(1, 2).contiguous().view(b*h, t, k)

In [47]:
ten2[h+1, 2]

tensor([18., 18.])

In [49]:
ten3[h+1, 2]

tensor([19., 19.])

Note that `ten2` and `ten3` are not the same

In [35]:
ten2.shape, ten3.shape

(torch.Size([15, 4, 2]), torch.Size([15, 4, 2]))

In [36]:
ten2

tensor([[[ 0.,  0.],
         [ 1.,  1.],
         [ 2.,  2.],
         [ 3.,  3.]],

        [[ 4.,  4.],
         [ 5.,  5.],
         [ 6.,  6.],
         [ 7.,  7.]],

        [[ 8.,  8.],
         [ 9.,  9.],
         [10., 10.],
         [11., 11.]],

        [[12., 12.],
         [13., 13.],
         [14., 14.],
         [15., 15.]],

        [[16., 16.],
         [17., 17.],
         [18., 18.],
         [19., 19.]],

        [[20., 20.],
         [21., 21.],
         [22., 22.],
         [23., 23.]],

        [[24., 24.],
         [25., 25.],
         [26., 26.],
         [27., 27.]],

        [[28., 28.],
         [29., 29.],
         [30., 30.],
         [31., 31.]],

        [[32., 32.],
         [33., 33.],
         [34., 34.],
         [35., 35.]],

        [[36., 36.],
         [37., 37.],
         [38., 38.],
         [39., 39.]],

        [[40., 40.],
         [41., 41.],
         [42., 42.],
         [43., 43.]],

        [[44., 44.],
         [45., 45.],
         [46

In [37]:
ten3

tensor([[[ 0.,  0.],
         [ 3.,  3.],
         [ 6.,  6.],
         [ 9.,  9.]],

        [[ 1.,  1.],
         [ 4.,  4.],
         [ 7.,  7.],
         [10., 10.]],

        [[ 2.,  2.],
         [ 5.,  5.],
         [ 8.,  8.],
         [11., 11.]],

        [[12., 12.],
         [15., 15.],
         [18., 18.],
         [21., 21.]],

        [[13., 13.],
         [16., 16.],
         [19., 19.],
         [22., 22.]],

        [[14., 14.],
         [17., 17.],
         [20., 20.],
         [23., 23.]],

        [[24., 24.],
         [27., 27.],
         [30., 30.],
         [33., 33.]],

        [[25., 25.],
         [28., 28.],
         [31., 31.],
         [34., 34.]],

        [[26., 26.],
         [29., 29.],
         [32., 32.],
         [35., 35.]],

        [[36., 36.],
         [39., 39.],
         [42., 42.],
         [45., 45.]],

        [[37., 37.],
         [40., 40.],
         [43., 43.],
         [46., 46.]],

        [[38., 38.],
         [41., 41.],
         [44

---

In [62]:
b, t, v = 2, 3, 4

In [63]:
ten = torch.arange(b*t*v)
ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])

In [65]:
ten = ten.view(b, t, v)
ten

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

If there are d dimensions, it holds d-1 dimensions fixed and iterates over the dth dimension like...

```
d1 d2 d3
 0  0  0
 0  0  1
 0  0  2
 0  0  3
 0  1  0
 0  1  1
    .
    .
    .
 0  2  3
 1  0  0
    .
    .
    .
```

Unexpected behavior with reshaping/viewing

In [61]:
ten2 = ten.view(b*v, t)
ten3 = ten.transpose(1, 2).contiguous().view(b*v, t)

Batch elements are now found with a stride of `v` along the 0th dimension

Batch 1:

In [69]:
ten[1].t()

tensor([[12, 16, 20],
        [13, 17, 21],
        [14, 18, 22],
        [15, 19, 23]])

In [66]:
ten2[v*1:v*2]

tensor([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]])

In [67]:
ten3[v*1:v*2]

tensor([[12, 16, 20],
        [13, 17, 21],
        [14, 18, 22],
        [15, 19, 23]])

---

```
cities, months, timeofday
c       m       t
```

In [70]:
c = 2
m = 3
t = 4

In [75]:
cities = {
    'denver': 0,
    'orlando': 1
}
months = {
    'january': 0,
    'february': 1,
    'march': 2
}
times = {
    'morning': 0,
    'afternoon': 1,
    'night': 2,
    'late-night'; 3
}

In [71]:
ten = torch.arange(c*m*t).view(c,m,t)
ten

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

Number of live bands playing in Denver in the Night for each Month

In [76]:
ten[cities['denver'], :, times['night']]

tensor([ 2,  6, 10])

Fold city and timeofday dimensions together

In [79]:
ten3_tmp = ten.transpose(1,2).contiguous()
ten3_tmp

tensor([[[ 0,  4,  8],
         [ 1,  5,  9],
         [ 2,  6, 10],
         [ 3,  7, 11]],

        [[12, 16, 20],
         [13, 17, 21],
         [14, 18, 22],
         [15, 19, 23]]])

In [80]:
ten2 = ten.view(c*t, m)
ten3 = ten3_tmp.view(c*t, m)
ten2.shape, ten3.shape

(torch.Size([8, 3]), torch.Size([8, 3]))

In [73]:
ten2

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]])

In [77]:
ten2[cities['denver']*t + times['night']]

tensor([6, 7, 8])

In [74]:
ten3

tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [12, 16, 20],
        [13, 17, 21],
        [14, 18, 22],
        [15, 19, 23]])

In [78]:
ten3[cities['denver']*t + times['night']]

tensor([ 2,  6, 10])

In [81]:
ten3.reshape(-1)

tensor([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11, 12, 16, 20, 13, 17, 21,
        14, 18, 22, 15, 19, 23])